apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-assessment.fullname" . }}-secret
  labels:
    {{- include "ai-assessment.labels" . | nindent 4 }}
type: Opaque
data:
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
